---
###Course Project 
The class project for [Getting and Cleaning Data](https://www.coursera.org/course/getdata) was to read in [Smartphone Data](http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones) and clean it to produce a tidy data. 

####Instructions 
1. There are three files in this repo: The R Script, The Code Book, and ReadMe file
2. The Code Book and ReadMe file provide details on how to run the script
3. Download the script: [run_analysis.R](https://github.com/jgallina/Getting-and-Cleaning-Data/blob/master/run_analysis.R) 
4. Run the script in R Studio 
5. Output is a space separated text file called 'tidy.txt'
5. The tidy.txt file may be reloaded into R Studio by running the last line of the script in `run_analysis.R`, that is `tidy <- read.table("./data/Tidy.txt")`  

####The following steps have been incorporated into the script

* Creation of a `data` folder in working directory to store files 
* Downloading project data in zip format, unzipping the files, and storing files in the `data` folder
* Detecting if the `dplr` and `data.table` package are installed. The script will install these packages if they are not already installed. 

### References and Further Reading   
[Getting and Cleaning Data Webpage](https://www.coursera.org/course/getdata)  

[Data for the course project](https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip)  

[Tidy Data by Hadley Wickham](www.jstatsoft.org/v59/i10/paper)

